[workspace]

members = [ "mpc", "spdz", "mpcauth", ]
resolver = "2"

[workspace.dependencies]
rand = "0.8.5"
ff = {version = "0.13", features = ["derive"]}
sha3 = "0.10.8"
bincode = "1.3.3"
rsa = "0.9.6"
serde = { version = "1.0.200", features = ["derive"] }
